packages:
  - packages/core/*
  - packages/internal/*
  - packages/storybook
  - packages/react
  - packages/apps/*

catalog:
  '@novawaveui/tailwind-composer': ^1.3.1
  '@react-aria/focus': 3.21.1
  '@react-aria/interactions': ^3.25.5
  '@react-aria/utils': 3.30.1
  '@react-types/shared': ^3.32.0
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  react: ^19.1.1
  react-dom: ^19.1.1
